# Generated by Django 4.2.6 on 2024-09-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcetto', '0004_developer_total_match_developer_win_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='image_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
