# Generated by Django 4.2.6 on 2024-09-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcetto', '0005_developer_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='description',
        ),
    ]
