# Generated by Django 4.2.6 on 2024-09-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcetto', '0006_remove_developer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='briscola_total_match',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='developer',
            name='briscola_total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='developer',
            name='briscola_win_match',
            field=models.IntegerField(default=0),
        ),
    ]
