# Generated by Django 4.2.6 on 2024-09-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcetto', '0007_developer_briscola_total_match_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='briscola_total_points',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='total_points',
        ),
    ]
