# Generated by Django 4.2.6 on 2024-10-14 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calcetto', '0008_remove_developer_briscola_total_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='params',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('loser_1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_loser_1', to='calcetto.developer')),
                ('loser_2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_loser_2', to='calcetto.developer')),
                ('winner_1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_winner_1', to='calcetto.developer')),
                ('winner_2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_winner_2', to='calcetto.developer')),
            ],
        ),
    ]
