# Generated by Django 4.2.6 on 2024-11-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcetto', '0009_developer_params_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='total_match_singolo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='developer',
            name='win_match_singolo',
            field=models.IntegerField(default=0),
        ),
    ]
