# Generated by Django 5.2 on 2025-04-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcetto', '0011_developer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='slack_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
